language: node_js

node_js:
  - 4
  - 5

addons:
  postgresql: 9.4

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-fi

before_script:
  - npm install
